"""Правки в Users

Revision ID: bd629c158040
Revises: 
Create Date: 2021-10-31 18:57:52.787403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd629c158040'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_key', sa.String(length=100), nullable=False))
    op.drop_column('users', 'nickname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('users', 'access_key')
    # ### end Alembic commands ###
